/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SheWell {
  export type UserStruct = { name: string; content: string; isExists: boolean };

  export type UserStructOutput = [
    name: string,
    content: string,
    isExists: boolean
  ] & { name: string; content: string; isExists: boolean };
}

export interface SheWellInterface extends Interface {
  getFunction(
    nameOrSignature: "getMyUserInfo" | "registerUser"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMyUserInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMyUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
}

export interface SheWell extends BaseContract {
  connect(runner?: ContractRunner | null): SheWell;
  waitForDeployment(): Promise<this>;

  interface: SheWellInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMyUserInfo: TypedContractMethod<[], [SheWell.UserStructOutput], "view">;

  registerUser: TypedContractMethod<
    [_name: string, _content: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMyUserInfo"
  ): TypedContractMethod<[], [SheWell.UserStructOutput], "view">;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [_name: string, _content: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
